id: P009241
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-19 19:29:34.983885
source_metadata:
  id: bdr:W17722
  title: བོད་གྱི་སྨན་པ་རིམ་བྱོན་གྱི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    bbf283017b25472ab16091db17a11621:
      image_group_id: I4791
      title: ''
      volume_number: 1
      total_pages: 672
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
