id: P009241
initial_creation_type: ocr
source_metadata:
  id: bdr:W17722
  title: བོད་གྱི་སྨན་པ་རིམ་བྱོན་གྱི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    bbf283017b25472ab16091db17a11621:
      image_group_id: I4791
      title: ''
      volume_number: 1
      total_pages: 672
