id: I9F6CE7E1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T08:44:50+00:00'
last_modified: '2022-06-08T09:37:07.240842+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W17722
  title: བོད་གྱི་སྨན་པ་རིམ་བྱོན་གྱི་རྣམ་ཐར་ཕྱོགས་བསྒྲིགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    F414:
      image_group_id: I4791
      title: ''
      total_pages: 672
      order: 1
      base_file: F414.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
